// Bidou AI Configuration Data
/**
 * BIDOU AI - Configuration Data
 * Initial provider models, default pricing packages, and seed telemetry.
 */

import { AiModelConfig, CreditPackage, ModelPerformanceTelemetry } from '../types';
import {
  DEFAULT_PRICING_FACTORS,
  computeCreditCost,
  computeVideoCreditCost,
  getModelCogsRatioOverride,
  getTierIllustration,
} from './pricingEngine';
import { IMAGE_ROUTES, MUSIC_PROVIDER_COST_USD, VEO_ROUTES, getPricingCostUsd } from './providerCatalog';

export const FREE_TIER_WELCOME_CREDITS = 500;

export const INITIAL_AI_MODELS: AiModelConfig[] = [
  // Cloudflare Workers AI Image Models (ship inactive until owner verifies commercial licensing)
  {
    id: 'img_cf_flux1_schnell',
    provider: 'cloudflare',
    model_name: 'cf_flux1_schnell',
    display_name: 'Cloudflare FLUX.1 Schnell (Fast 1K)',
    generation_type: 'image',
    pricing_kind: 'per_image',
    unit: 'per_generation',
    provider_cost: getPricingCostUsd('img_cf_flux1_schnell'),
    credit_cost: computeCreditCost(getPricingCostUsd('img_cf_flux1_schnell'), 'image').creditCost,
    active: false,
    quality_tier: 'lite',
    licensing_verified: false,
    promo_eligible: true,
    is_premium: false,
    max_concurrent_variants: 4,
    max_upscale: '1k',
    upscale_credit_cost: 35,
    supported_aspect_ratios: ['1:1'],
    suppliers: [
      {
        supplier: 'cloudflare',
        upstream_model: '@cf/black-forest-labs/flux-1-schnell',
        priority: 1,
        env: 'both',
        enabled: true,
      },
    ],
    prompt_style_guide: 'FLUX.1 Schnell (4-step distilled). Concise visual description with clear subject and lighting. Outputs square 1024x1024.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'img_cf_flux2_klein_4b',
    provider: 'cloudflare',
    model_name: 'cf_flux2_klein_4b',
    display_name: 'Cloudflare FLUX.2 Klein 4B (1K)',
    generation_type: 'image',
    pricing_kind: 'per_image',
    unit: 'per_generation',
    provider_cost: getPricingCostUsd('img_cf_flux2_klein_4b'),
    credit_cost: computeCreditCost(getPricingCostUsd('img_cf_flux2_klein_4b'), 'image').creditCost,
    active: false,
    quality_tier: 'fast',
    licensing_verified: false,
    promo_eligible: true,
    is_premium: false,
    max_concurrent_variants: 4,
    max_upscale: '2k',
    upscale_credit_cost: 50,
    supported_aspect_ratios: ['1:1', '16:9', '9:16'],
    suppliers: [
      {
        supplier: 'cloudflare',
        upstream_model: '@cf/black-forest-labs/flux-2-klein-4b',
        priority: 1,
        env: 'both',
        enabled: true,
      },
    ],
    prompt_style_guide: 'FLUX.2 Klein 4B. Supports custom width/height aspect ratios at 1MP resolution with strong prompt adherence and natural lighting.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Image Models (Google)
  {
    id: 'img_nano_banana_2_lite',
    provider: 'google',
    model_name: 'nano_banana_2_lite',
    display_name: 'Nano Banana 2 Lite (Fast 1K)',
    generation_type: 'image',
    pricing_kind: 'per_image',
    unit: 'per_generation',
    provider_cost: IMAGE_ROUTES.nano_banana_2_lite.providerCostUsd,
    credit_cost: computeCreditCost(IMAGE_ROUTES.nano_banana_2_lite.providerCostUsd, 'image').creditCost,
    active: true,
    quality_tier: 'lite',
    licensing_verified: true,
    promo_eligible: true,
    is_premium: false,
    max_concurrent_variants: 4,
    max_upscale: '1k',
    upscale_credit_cost: 35,
    suppliers: [
      {
        supplier: 'google',
        upstream_model: IMAGE_ROUTES.nano_banana_2_lite.googleModelId,
        priority: 1,
        env: 'both',
        enabled: true,
      },
    ],
    prompt_style_guide: 'Fast 1K image model. Favour one clear subject, explicit lighting, explicit lens/camera framing, and a short comma-separated descriptor chain. Avoid multi-scene narratives, avoid embedded text, avoid more than two named subjects.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'img_nano_banana_2',
    provider: 'google',
    model_name: 'nano_banana_2',
    display_name: 'Nano Banana 2 (HQ 1K)',
    generation_type: 'image',
    pricing_kind: 'per_image',
    unit: 'per_generation',
    provider_cost: IMAGE_ROUTES.nano_banana_2.providerCostUsd,
    credit_cost: computeCreditCost(IMAGE_ROUTES.nano_banana_2.providerCostUsd, 'image').creditCost,
    active: true,
    quality_tier: 'fast',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 4,
    max_upscale: '2k',
    upscale_credit_cost: 70,
    suppliers: [
      {
        supplier: 'google',
        upstream_model: IMAGE_ROUTES.nano_banana_2.googleModelId,
        priority: 1,
        env: 'both',
        enabled: true,
      },
    ],
    prompt_style_guide: 'High-quality 1K image model. Handles material detail, texture and complex lighting well. Use photographic vocabulary (focal length, aperture, film stock, time of day). Keep composition to a single coherent frame.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'img_nano_banana_pro',
    provider: 'google',
    model_name: 'nano_banana_pro',
    display_name: 'Nano Banana Pro (Cinematic 2K)',
    generation_type: 'image',
    pricing_kind: 'per_image',
    unit: 'per_generation',
    provider_cost: IMAGE_ROUTES.nano_banana_pro.providerCostUsd,
    credit_cost: computeCreditCost(IMAGE_ROUTES.nano_banana_pro.providerCostUsd, 'image').creditCost,
    active: true,
    quality_tier: 'pro',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: true,
    max_concurrent_variants: 2,
    max_upscale: '4k',
    upscale_credit_cost: 140,
    suppliers: [
      {
        supplier: 'google',
        upstream_model: IMAGE_ROUTES.nano_banana_pro.googleModelId,
        priority: 1,
        env: 'both',
        enabled: true,
      },
    ],
    prompt_style_guide: 'Cinematic 2K flagship. Rewards dense art-direction: colour grade, production design, atmosphere, depth cues, secondary light sources. Can hold two or three subjects and legible signage. Write like a cinematographer\'s shot note.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Video Models (Veo 3.1 — Kie.ai priority 1, Google direct priority 2)
  {
    id: 'vid_veo_3_1_lite',
    provider: 'google',
    model_name: 'veo_3_1_lite',
    display_name: 'Google Veo 3.1 Lite (720p)',
    generation_type: 'video',
    pricing_kind: 'per_clip',
    unit: 'per_second',
    provider_cost: VEO_ROUTES.veo_3_1_lite.ratePerSecondUsd['720p'], // 720p base rate; 1080p handled by VEO_ROUTES
    credit_cost: computeVideoCreditCost(VEO_ROUTES.veo_3_1_lite.ratePerSecondUsd['720p'], 8, '720p', true, 'veo_3_1_lite'), // default 8s @ 720p
    active: true,
    quality_tier: 'lite',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 4,
    max_upscale: '1080p',
    upscale_credit_cost: 220,
    supported_aspect_ratios: ['16:9', '9:16'],
    video_options: {
      resolutions: ['720p', '1080p'],
      durations: [4, 6, 8],
    },
    suppliers: [
      // TODO(Phase 3): Confirm exact Kie.ai Veo 3.1 Lite upstream_model slug in docs.kie.ai/veo3-api (e.g. 'veo3_lite' vs mode parameter) before enabling in live Kie adapter
      { supplier: 'kie', upstream_model: 'veo3_lite', priority: 1, env: 'both', enabled: true },
      { supplier: 'google', upstream_model: VEO_ROUTES.veo_3_1_lite.googleModelId, priority: 2, env: 'both', enabled: true },
    ],
    prompt_style_guide: 'Veo 3.1 Lite, 720p, 5-8s. Describe ONE continuous camera move and ONE action beat. State camera motion explicitly (slow dolly in, handheld pan left, static locked-off). Do not request cuts, scene changes, or on-screen text.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'vid_veo_3_1_fast',
    provider: 'google',
    model_name: 'veo_3_1_fast',
    display_name: 'Google Veo 3.1 Fast (Smooth 720p)',
    generation_type: 'video',
    pricing_kind: 'per_clip',
    unit: 'per_second',
    provider_cost: VEO_ROUTES.veo_3_1_fast.ratePerSecondUsd['720p'],
    credit_cost: computeVideoCreditCost(VEO_ROUTES.veo_3_1_fast.ratePerSecondUsd['720p'], 8, '720p', true, 'veo_3_1_fast'), // default 8s @ 720p
    active: true,
    quality_tier: 'fast',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 2,
    max_upscale: '1080p',
    upscale_credit_cost: 260,
    supported_aspect_ratios: ['16:9', '9:16'],
    video_options: {
      resolutions: ['720p', '1080p'],
      durations: [4, 6, 8],
    },
    suppliers: [
      { supplier: 'kie', upstream_model: 'veo3_fast', priority: 1, env: 'both', enabled: true },
      { supplier: 'google', upstream_model: VEO_ROUTES.veo_3_1_fast.googleModelId, priority: 2, env: 'both', enabled: true },
    ],
    prompt_style_guide: 'Veo 3.1 Fast, smooth 720p. Same single-shot discipline as Lite, but motion fidelity is higher — specify subject velocity and camera velocity separately. Ambient audio cues are honoured; name them.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'vid_veo_3_1_standard',
    provider: 'google',
    model_name: 'veo_3_1_standard',
    display_name: 'Google Veo 3.1 Cinematic (Studio Tier)',
    generation_type: 'video',
    pricing_kind: 'per_clip',
    unit: 'per_second',
    provider_cost: VEO_ROUTES.veo_3_1_standard.ratePerSecondUsd['720p'],
    credit_cost: computeVideoCreditCost(VEO_ROUTES.veo_3_1_standard.ratePerSecondUsd['720p'], 8, '720p', true, 'veo_3_1_standard'), // default 8s @ 720p
    active: true,
    quality_tier: 'standard',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: true,
    max_concurrent_variants: 1,
    max_upscale: '4k',
    upscale_credit_cost: 480,
    supported_aspect_ratios: ['16:9', '9:16'],
    video_options: {
      resolutions: ['720p', '1080p'],
      durations: [4, 6, 8],
    },
    suppliers: [
      { supplier: 'kie', upstream_model: 'veo3', priority: 1, env: 'both', enabled: true },
      { supplier: 'google', upstream_model: VEO_ROUTES.veo_3_1_standard.googleModelId, priority: 2, env: 'both', enabled: true },
    ],
    prompt_style_guide: 'Veo 3.1 Cinematic. Full shot-list vocabulary: lens, camera movement, blocking, lighting setup, grade, diegetic audio. Still ONE continuous take. Highest adherence to art-direction language of any video model in the catalogue.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Video Models (Alibaba Wan 3.0 — ship inactive until owner verifies commercial licensing)
  {
    id: 'vid_wan_3_0_standard',
    provider: 'alibaba',
    model_name: 'wan_3_0_standard',
    display_name: 'Alibaba Wan 3.0 Standard',
    generation_type: 'video',
    pricing_kind: 'per_second',
    unit: 'per_second',
    provider_cost: getPricingCostUsd('vid_wan_3_0_standard', { resolution: '720p', durationSeconds: 1 }),
    credit_cost: computeVideoCreditCost(0.10, 5, '720p', true, 'wan_3_0_standard'), // default 5s @ 720p = 770 credits
    active: false,
    quality_tier: 'standard',
    licensing_verified: false,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 2,
    max_upscale: '1080p',
    upscale_credit_cost: 260,
    supported_aspect_ratios: ['16:9', '9:16', '1:1'],
    video_options: {
      resolutions: ['480p', '720p', '1080p'],
      durations: { min: 2, max: 30, step: 1 },
      max_duration_by_plan: {
        free: 15,
        starter: 15,
        creator: 15,
        pro: 30,
        studio: 30,
      },
    },
    suppliers: [
      {
        supplier: 'alibaba',
        upstream_model: 'wan3.0-t2v-std',
        priority: 1,
        env: 'both',
        enabled: true,
      },
    ],
    prompt_style_guide: 'Alibaba Wan 3.0 Standard (2–30s). Supports 480p, 720p, and 1080p with coherent long-take motion. Clips over 15s require Pro or Studio tier.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'vid_wan_3_0_prime',
    provider: 'alibaba',
    model_name: 'wan_3_0_prime',
    display_name: 'Alibaba Wan 3.0 Prime (Fast)',
    generation_type: 'video',
    pricing_kind: 'per_second',
    unit: 'per_second',
    provider_cost: getPricingCostUsd('vid_wan_3_0_prime', { resolution: '720p', durationSeconds: 1 }),
    credit_cost: computeVideoCreditCost(0.14, 5, '720p', true, 'wan_3_0_prime'), // default 5s @ 720p = 1080 credits
    active: false,
    quality_tier: 'pro',
    licensing_verified: false,
    promo_eligible: false,
    is_premium: true,
    max_concurrent_variants: 2,
    max_upscale: '1080p',
    upscale_credit_cost: 260,
    supported_aspect_ratios: ['16:9', '9:16', '1:1'],
    video_options: {
      resolutions: ['480p', '720p', '1080p'],
      durations: { min: 2, max: 30, step: 1 },
      max_duration_by_plan: {
        free: 15,
        starter: 15,
        creator: 15,
        pro: 30,
        studio: 30,
      },
    },
    suppliers: [
      {
        supplier: 'alibaba',
        upstream_model: 'wan3.0-t2v-prime',
        priority: 1,
        env: 'both',
        enabled: true,
      },
    ],
    prompt_style_guide: 'Alibaba Wan 3.0 Prime (Fast 2–30s). Accelerated high-fidelity synthesis across 480p, 720p, and 1080p. Clips over 15s require Pro or Studio tier.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Music Models (musicapi.ai)
  // Legacy internal id: mus_lyria_3_pro; product is Sonic v4.5 (Full Studio)
  {
    id: 'mus_lyria_3_pro',
    provider: 'musicapi',
    model_name: 'lyria_3_pro',
    // TODO(owner): model was labelled "Google Lyria 3 Pro" in prior display_name, but its only supplier is MusicAPI/Sonic.
    display_name: 'Sonic v4.5 (Full Studio)',
    generation_type: 'music',
    pricing_kind: 'per_song',
    unit: 'per_song',
    provider_cost: MUSIC_PROVIDER_COST_USD.lyria_3_pro,
    credit_cost: computeCreditCost(MUSIC_PROVIDER_COST_USD.lyria_3_pro, 'music').creditCost, // per TASK (2 takes included)
    active: true,
    quality_tier: 'fast',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 2,
    max_upscale: '1080p',
    upscale_credit_cost: 0,
    // Source of truth is the model_suppliers table (admin can edit). This is only the catalogue fallback.
    suppliers: [
      { supplier: 'musicapi', upstream_model: 'sonic-v4-5', priority: 1, env: 'both', enabled: true },
    ],
    prompt_style_guide: 'Sonic v4.5 Full Studio. Describe the story the lyrics should tell, plus instrumentation, tempo feel and vocal delivery. Genre and mood are provided as context and should be reflected in the arrangement.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  // Legacy internal id: mus_suno_sonic_v5; product is Sonic v5 (Vocalist Master)
  {
    id: 'mus_suno_sonic_v5',
    provider: 'musicapi',
    model_name: 'suno_sonic_v5',
    display_name: 'Sonic v5 (Vocalist Master)',
    generation_type: 'music',
    pricing_kind: 'per_song',
    unit: 'per_song',
    provider_cost: MUSIC_PROVIDER_COST_USD.suno_sonic_v5,
    credit_cost: computeCreditCost(
      MUSIC_PROVIDER_COST_USD.suno_sonic_v5,
      'music',
      DEFAULT_PRICING_FACTORS,
      getModelCogsRatioOverride('mus_suno_sonic_v5')
    ).creditCost, // per TASK (2 takes included)
    active: true,
    quality_tier: 'pro',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 2,
    max_upscale: '1080p',
    upscale_credit_cost: 0,
    // Source of truth is the model_suppliers table (admin can edit). This is only the catalogue fallback.
    suppliers: [
      { supplier: 'musicapi', upstream_model: 'sonic-v5', priority: 1, env: 'both', enabled: true },
    ],
    prompt_style_guide: 'Sonic v5, vocalist-forward master. Describe the story the lyrics should tell, plus instrumentation, tempo feel and vocal delivery. Genre and mood are provided as context and should be reflected in the arrangement.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'mus_suno_v6',
    provider: 'sunor',
    model_name: 'suno_v6',
    display_name: 'Suno V6 (Flagship Studio)',
    generation_type: 'music',
    pricing_kind: 'per_song',
    unit: 'per_song',
    provider_cost: MUSIC_PROVIDER_COST_USD.suno_v6,
    credit_cost: computeCreditCost(
      MUSIC_PROVIDER_COST_USD.suno_v6,
      'music',
      DEFAULT_PRICING_FACTORS,
      getModelCogsRatioOverride('mus_suno_v6')
    ).creditCost, // 410 credits per TASK (2 takes included, 0.20 target COGS ratio)
    active: true,
    quality_tier: 'pro',
    licensing_verified: true,
    promo_eligible: false,
    is_premium: true,
    max_concurrent_variants: 2,
    max_upscale: '1080p',
    upscale_credit_cost: 0,
    suppliers: [
      { supplier: 'sunor', upstream_model: 'suno', priority: 1, env: 'both', enabled: true },
    ],
    prompt_style_guide: 'Suno V6 flagship via Sunor. Supports both inspiration mode (rich style description) and custom lyrics mode with [Verse], [Chorus], and [Bridge] tags, expressive vocals, and full studio arrangement.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // Future / Alternate Providers (Phase 9 - Manual licensing review required!)
  {
    id: 'vid_kuaishou_kling',
    provider: 'kuaishou',
    model_name: 'kling_1_5',
    display_name: 'Kling 1.5 Video (Fallback Candidate)',
    generation_type: 'video',
    unit: 'per_second',
    provider_cost: 0.07,
    credit_cost: computeVideoCreditCost(0.07, 8, '720p', true),
    active: false, // Locked until licensing_verified
    quality_tier: 'fast',
    licensing_verified: false, // Hard UI gate: Cannot be activated until reviewed
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 2,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'vid_bytedance_seedance',
    provider: 'bytedance',
    model_name: 'seedance_v1',
    display_name: 'Seedance Video (Fallback Candidate)',
    generation_type: 'video',
    unit: 'per_second',
    provider_cost: 0.06,
    credit_cost: computeVideoCreditCost(0.06, 8, '720p', true),
    active: false,
    quality_tier: 'lite',
    licensing_verified: false,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 2,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'voi_elevenlabs_tales',
    provider: 'elevenlabs',
    model_name: 'eleven_multilingual_v2',
    display_name: 'ElevenLabs Voice & African Tales Narration',
    generation_type: 'voice',
    unit: 'per_generation',
    provider_cost: 0.04,
    credit_cost: computeCreditCost(0.04, 'voice').creditCost,
    active: false,
    quality_tier: 'pro',
    licensing_verified: false,
    promo_eligible: false,
    is_premium: false,
    max_concurrent_variants: 1,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_PACKAGES: CreditPackage[] = [
  // =========================================================================
  // Unified 4-Tier Ladder (Task 8 / Part B.1) - Active Catalogue
  // =========================================================================
  {
    id: 'pkg_starter',
    name: 'Starter',
    tier: 'starter',
    price_fcfa: 2000,
    credits: 1500,
    active: true,
    estimated_generations: getTierIllustration(1500, 'mixed', INITIAL_AI_MODELS),
    features: [
      '1,500 Universal Credits',
      'High-resolution downloads',
      'Full access to Image, Video & Music studios',
      'Local Mobile Money instant checkout',
    ],
  },
  {
    id: 'pkg_creator',
    name: 'Creator',
    tier: 'creator',
    price_fcfa: 5400,
    credits: 5500,
    popular: true,
    active: true,
    estimated_generations: getTierIllustration(5500, 'mixed', INITIAL_AI_MODELS),
    features: [
      '5,500 Universal Credits',
      'Priority GPU cluster queue',
      'Cinematic 2K upscales & HD video',
      'Commercial creator rights',
    ],
  },
  {
    id: 'pkg_pro',
    name: 'Pro',
    tier: 'pro',
    price_fcfa: 16000,
    credits: 18000,
    active: true,
    estimated_generations: getTierIllustration(18000, 'mixed', INITIAL_AI_MODELS),
    features: [
      '18,000 Universal Credits',
      'Full 4K Ultra-HD & 60fps video synthesis',
      'Full studio tracks & lyrics AI',
      'Direct WhatsApp & social media exports',
    ],
  },
  {
    id: 'pkg_studio',
    name: 'Studio',
    tier: 'studio',
    price_fcfa: 42000,
    credits: 53000,
    active: true,
    estimated_generations: getTierIllustration(53000, 'mixed', INITIAL_AI_MODELS),
    features: [
      '53,000 Universal Credits',
      'Highest GPU cluster priority',
      'Multi-project team collaboration',
      'Dedicated account manager support',
    ],
  },

  // =========================================================================
  // Legacy per-media packs (active: false - preserved for historical ID lookups)
  // =========================================================================
  // Image Packages (Legacy)
  {
    id: 'pkg_img_starter',
    media_tab: 'image',
    tier: 'starter',
    name: 'Image Starter',
    price_fcfa: 1500,
    credits: 1500,
    active: false,
    estimated_generations: [
      { label: 'Standard Images (Nano Banana Lite)', count: 21 },
      { label: 'Premium Images (Nano Banana HQ)', count: 10 },
    ],
    features: [
      '1,500 Universal Credits',
      'High-resolution downloads',
      'Commercial usage included',
      'Fast Google Cloud inference',
    ],
  },
  {
    id: 'pkg_img_creator',
    media_tab: 'image',
    tier: 'creator',
    name: 'Image Creator',
    price_fcfa: 3500,
    credits: 3800,
    active: false,
    estimated_generations: [
      { label: 'Standard Images (Nano Banana Lite)', count: 54 },
      { label: 'Premium Images (Nano Banana HQ)', count: 27 },
      { label: 'Pro Cinematic 2K', count: 13 },
    ],
    features: [
      '3,800 Universal Credits (Bonus included)',
      'Cinematic 2K upscale support',
      'Priority queue processing',
      'Dedicated project folders',
    ],
  },
  {
    id: 'pkg_img_pro',
    media_tab: 'image',
    tier: 'pro',
    name: 'Image Pro',
    price_fcfa: 7000,
    credits: 8500,
    active: false,
    estimated_generations: [
      { label: 'Standard Images (Nano Banana Lite)', count: 121 },
      { label: 'Premium Images (Nano Banana HQ)', count: 60 },
      { label: 'Pro Cinematic 2K', count: 30 },
    ],
    features: [
      '8,500 Universal Credits (Best value)',
      'Full 4K Ultra-HD options',
      'Private mode (no showcase)',
      'Direct WhatsApp status & social exports',
    ],
  },

  // Video Packages (Legacy)
  {
    id: 'pkg_vid_starter',
    media_tab: 'video',
    tier: 'starter',
    name: 'Video Starter',
    price_fcfa: 4000,
    credits: 4000,
    active: false,
    estimated_generations: [
      { label: 'Veo 3.1 Lite (8s clips)', count: 8 },
      { label: 'Veo 3.1 Fast (8s clips)', count: 4 },
    ],
    features: [
      '4,000 Universal Credits',
      '720p HD generation with audio',
      'Text-to-Video and Image-to-Video',
      'Zero Cloudflare R2 egress fees',
    ],
  },
  {
    id: 'pkg_vid_creator',
    media_tab: 'video',
    tier: 'creator',
    name: 'Video Creator',
    price_fcfa: 9000,
    credits: 10000,
    active: false,
    estimated_generations: [
      { label: 'Veo 3.1 Lite (8s clips)', count: 20 },
      { label: 'Veo 3.1 Fast (8s clips)', count: 10 },
    ],
    features: [
      '10,000 Universal Credits (+1,000 bonus)',
      'Smooth 60fps frame synthesis',
      'Aspect ratio presets (16:9, 9:16, 1:1)',
      'Prompt enhancer assistance',
    ],
  },
  {
    id: 'pkg_vid_pro',
    media_tab: 'video',
    tier: 'pro',
    name: 'Video Pro',
    price_fcfa: 20000,
    credits: 24000,
    active: false,
    estimated_generations: [
      { label: 'Veo 3.1 Lite (8s clips)', count: 50 },
      { label: 'Veo 3.1 Fast (8s clips)', count: 25 },
      { label: 'Veo 3.1 Cinematic Standard', count: 6 },
    ],
    features: [
      '24,000 Universal Credits',
      'Priority GPU cluster scheduling',
      '1080p full high-definition exports',
      'Full commercial license',
    ],
  },
  {
    id: 'pkg_vid_studio',
    media_tab: 'video',
    tier: 'studio',
    name: 'Video Studio',
    price_fcfa: 45000,
    credits: 60000,
    active: false,
    estimated_generations: [
      { label: 'Veo 3.1 Lite (8s clips)', count: 125 },
      { label: 'Veo 3.1 Fast (8s clips)', count: 62 },
      { label: 'Veo 3.1 Cinematic Standard', count: 15 },
    ],
    features: [
      '60,000 Universal Credits (Bulk discount)',
      'Multi-project management',
      'Highest queue priority',
      'Direct account manager support',
    ],
  },

  // Music Packages (Legacy)
  {
    id: 'pkg_mus_starter',
    media_tab: 'music',
    tier: 'starter',
    name: 'Music Starter',
    price_fcfa: 2000,
    credits: 2000,
    active: false,
    estimated_generations: [
      { label: 'Full Studio Tracks (2 Takes each)', count: 9 },
    ],
    features: [
      '2,000 Universal Credits',
      'Sonic v4.5 / Sonic v5',
      '2 generated takes per song request',
      'African & Western genre coverage',
    ],
  },
  {
    id: 'pkg_mus_creator',
    media_tab: 'music',
    tier: 'creator',
    name: 'Music Creator',
    price_fcfa: 4500,
    credits: 5000,
    active: false,
    estimated_generations: [
      { label: 'Full Studio Tracks (2 Takes each)', count: 22 },
    ],
    features: [
      '5,000 Universal Credits (+500 bonus)',
      'AI Lyrics generation with tonality controls',
      'Makossa, Bikutsi, Amapiano, Afrobeats & Mbolé presets',
      'Separated Cover Art trigger available',
    ],
  },
  {
    id: 'pkg_mus_pro',
    media_tab: 'music',
    tier: 'pro',
    name: 'Music Pro',
    price_fcfa: 9000,
    credits: 11000,
    active: false,
    estimated_generations: [
      { label: 'Full Studio Tracks (2 Takes each)', count: 50 },
    ],
    features: [
      '11,000 Universal Credits (+2,000 bonus)',
      'Publish-ready package export',
      'Lyrics AI-rewrite eligible (300 FCFA)',
      'Spotify / WhatsApp Status / YouTube export kit',
    ],
  },
];

export const INITIAL_TELEMETRY: Record<string, ModelPerformanceTelemetry> = {
  img_nano_banana_2_lite: {
    id: 'tel_1',
    model_id: 'img_nano_banana_2_lite',
    average_completion_seconds: 4.2,
    total_runs: 1420,
    failure_rate_percentage: 1.2,
    last_updated: '2026-09-17T00:00:00Z',
  },
  img_nano_banana_2: {
    id: 'tel_2',
    model_id: 'img_nano_banana_2',
    average_completion_seconds: 6.8,
    total_runs: 980,
    failure_rate_percentage: 1.8,
    last_updated: '2026-09-17T00:00:00Z',
  },
  vid_veo_3_1_lite: {
    id: 'tel_3',
    model_id: 'vid_veo_3_1_lite',
    average_completion_seconds: 28.5,
    total_runs: 640,
    failure_rate_percentage: 4.1,
    last_updated: '2026-09-17T00:00:00Z',
  },
  vid_veo_3_1_fast: {
    id: 'tel_4',
    model_id: 'vid_veo_3_1_fast',
    average_completion_seconds: 45.0,
    total_runs: 410,
    failure_rate_percentage: 5.2,
    last_updated: '2026-09-17T00:00:00Z',
  },
  mus_lyria_3_pro: {
    id: 'tel_5',
    model_id: 'mus_lyria_3_pro',
    average_completion_seconds: 18.0,
    total_runs: 1250,
    failure_rate_percentage: 2.3,
    last_updated: '2026-09-17T00:00:00Z',
  },
};
